apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongo.fullname" . }}-data-config
  labels:
    app.kubernetes.io/name: {{ include "mongo.name" . }}
    helm.sh/chart: {{ include "mongo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- (.Files.Glob "samples/*").AsConfig | nindent 2 }}
