# Default values for sse2rserve.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

connector:
  image:
    repository: analyticsearth/sse2rserve
    tag: latest
    pullPolicy: Always
    resources: {}

rserve:
  image:
    repository: analyticsearth/rservewithpackages
    tag: latest
    pullPolicy: Always
    resources: {}

poolNodes: "127.0.0.1:6311:1"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 50051

horizontalPodAutoscaler:
  enabled: false
  minReplicaCount: 1
  maxReplicaCount: 5
  targetCPUUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

affinity: {}
