---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ include "sse2rserve.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "sse2rserve.name" . }}
data:
  sse2rserve_rservePoolNodes: "{{ .Values.poolNodes }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sse2rserve.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sse2rserve.name" . }}
    helm.sh/chart: {{ include "sse2rserve.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sse2rserve.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sse2rserve.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-connector
          image: "{{ .Values.connector.image.repository }}:{{ .Values.connector.image.tag }}"
          imagePullPolicy: {{ .Values.connector.image.pullPolicy }}
          env:
            - name: sse2rserve_rservePoolNodes
              valueFrom:
                configMapKeyRef:
                  key: sse2rserve_rservePoolNodes
                  name: {{ include "sse2rserve.fullname" . }}-config
          ports:
            - name: qlik-sse
              containerPort: 50051
              protocol: TCP
          resources:
            {{- toYaml .Values.connector.resources | nindent 12 }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.rserve.image.repository }}:{{ .Values.rserve.image.tag }}"
          imagePullPolicy: {{ .Values.rserve.image.pullPolicy }}
          resources:
            {{- toYaml .Values.rserve.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
