apiVersion: v1
kind: Service
metadata:
  name: {{ include "qlik2datarobot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "qlik2datarobot.name" . }}
    helm.sh/chart: {{ include "qlik2datarobot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    prometheus.io/port: "19345"
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 50052
      protocol: TCP
      name: qlik-sse-qlik2datarobot
  selector:
    app.kubernetes.io/name: {{ include "qlik2datarobot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
